pull_request_rules:
  - name: auto-merge PRs created by nihaltp on snyk-upgrade-* branches
    conditions:
      - author=nihaltp
      - head~=^snyk-upgrade-.*$
      - "#check-failure=0"
      - "#check-pending=0"
      - "-conflict"
      - "#approved-reviews-by>=0"
    actions:
      merge:
        method: squash
      delete_head_branch: true
